"use client";

import { useState } from "react";
import Link from "next/link";
import {
  BarChart3,
  GitBranch,
  FileText,
  Target,
  Globe,
  Compass,
  CheckCircle,
  ArrowUpRight,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { DotField } from "@/components/ui/react-bits/dot-field";

const PREVIEW_TABS = [
  { id: "score", name: "Developer Score", icon: BarChart3, color: "text-blue-600" },
  { id: "github", name: "GitHub Analysis", icon: GitBranch, color: "text-cyan-600" },
  { id: "resume", name: "Resume Analysis", icon: FileText, color: "text-purple-600" },
  { id: "skills", name: "Skill Gap Analysis", icon: Target, color: "text-pink-600" },
  { id: "portfolio", name: "Portfolio Score", icon: Globe, color: "text-emerald-600" },
  { id: "readiness", name: "Career Readiness", icon: Compass, color: "text-indigo-600" },
];

export function ProductPreview() {
  const [activeTab, setActiveTab] = useState("score");

  return (
    <section id="preview" className="relative py-16 sm:py-20 border-t border-[var(--border)] bg-[var(--background)] overflow-hidden">
      {/* Official React Bits DotField Interactive Telemetry Grid */}
      <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden opacity-40">
        <DotField
          dotRadius={1.2}
          dotSpacing={18}
          cursorRadius={300}
          cursorForce={0.12}
          bulgeStrength={40}
          glowRadius={120}
          sparkle={false}
          waveAmplitude={0}
          gradientFrom="rgba(37, 99, 235, 0.22)"
          gradientTo="rgba(79, 70, 229, 0.12)"
          glowColor="rgba(37, 99, 235, 0.18)"
        />
      </div>

      {/* Glow behind intelligence engine workspace */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[450px] bg-gradient-to-r from-blue-500/6 via-indigo-500/5 to-cyan-500/6 rounded-full blur-[140px] pointer-events-none" />

      <div className="relative mx-auto max-w-6xl px-6 z-10">
        
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-2xl mx-auto"
        >
          <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-blue-50 border border-blue-200 px-3.5 py-1 text-[10px] font-bold text-blue-700 uppercase tracking-widest shadow-xs">
            Live Intelligence Engine
          </div>
          <h2 className="text-3xl font-extrabold tracking-tight sm:text-4xl text-[#0f172a]">
            Explore the AI Workspace
          </h2>
          <p className="mt-4 text-sm sm:text-base text-[#334155] leading-relaxed font-normal">
            Get telemetry-driven insights inside a unified dashboard. Explore the interactive modules below to see the depth of analysis generated by DevLeveler.
          </p>
        </motion.div>

        {/* Dashboard Preview Shell */}
        <div className="mt-10 sm:mt-12 grid gap-8 lg:grid-cols-12 items-start">
          
          {/* Left Tabs Menu */}
          <div className="lg:col-span-4 flex flex-row lg:flex-col overflow-x-auto lg:overflow-x-visible gap-1.5 bg-slate-50 p-2 rounded-2xl border border-slate-200 hide-scrollbar shrink-0 shadow-xs">
            {PREVIEW_TABS.map((tab) => {
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-3.5 px-4.5 py-3.5 rounded-xl text-left text-xs font-bold whitespace-nowrap transition-all duration-200 flex-1 lg:flex-none relative ${
                    isActive 
                      ? "text-blue-700" 
                      : "text-[#334155] hover:text-[#0f172a]"
                  }`}
                >
                  {isActive && (
                    <motion.div
                      layoutId="preview-active-pill"
                      className="absolute inset-0 bg-white border border-slate-200/90 rounded-xl shadow-xs"
                      transition={{ type: "spring", stiffness: 350, damping: 25 }}
                    />
                  )}
                  <tab.icon className={`h-4.5 w-4.5 shrink-0 relative z-10 transition-colors duration-200 ${isActive ? "text-blue-700" : "text-[#64748b]"}`} />
                  <span className="relative z-10">{tab.name}</span>
                </button>
              );
            })}
          </div>

          {/* Right Preview Card Workspace */}
          <div className="lg:col-span-8 bg-white border border-slate-200/90 rounded-2xl p-6 shadow-xl relative min-h-[380px] flex flex-col justify-between overflow-hidden backdrop-blur-md">
            
            {/* Window Header with Live Engine Indicator */}
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-6">
              <div className="flex items-center gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                <div className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
                <span className="text-[10px] font-mono text-[#475569] ml-2">devleveler.com/workspace/{activeTab}</span>
              </div>
              <div className="flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-[9px] font-bold text-emerald-700 font-mono shadow-xs">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
                ENGINE ONLINE
              </div>
            </div>

            {/* Content Previews */}
            <div className="flex-1 flex flex-col justify-center">
              <AnimatePresence mode="wait">
                
                {/* 1. Developer Score */}
                {activeTab === "score" && (
                  <motion.div
                    key="score"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-6 md:grid-cols-12 items-center"
                  >
                    <div className="md:col-span-5 flex flex-col items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-6 shadow-inner">
                      <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest">AI Readiness Score</span>
                      <div className="relative flex items-center justify-center w-32 h-32 mt-5">
                        <svg width="120" height="120" viewBox="0 0 100 100">
                          <circle cx="50" cy="50" r="42" fill="none" stroke="rgba(0,0,0,0.06)" strokeWidth="6" />
                          <circle cx="50" cy="50" r="42" fill="none" stroke="url(#demoScoreGradient)" strokeWidth="6" strokeDasharray="263.8" strokeDashoffset="42" transform="rotate(-90 50 50)" strokeLinecap="round" />
                          <defs>
                            <linearGradient id="demoScoreGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                              <stop offset="0%" stopColor="#004ac6" />
                              <stop offset="100%" stopColor="#7c3aed" />
                            </linearGradient>
                          </defs>
                        </svg>
                        <span className="absolute text-3.5xl font-black text-[var(--foreground)] tracking-tighter">84</span>
                      </div>
                      <span className="text-[10px] text-emerald-600 font-bold mt-4">Level 4: Professional Builder</span>
                    </div>
                    
                    <div className="md:col-span-7 space-y-4">
                      <div>
                        <h4 className="text-sm font-extrabold text-[var(--foreground)] mb-1.5">Telemetry Weights Breakdown</h4>
                        <p className="text-xs text-[var(--foreground-secondary)] leading-relaxed">
                          Your overall score weights core telemetry inputs across commits, clean code architecture, and deployment tests.
                        </p>
                      </div>
                      <div className="space-y-3.5">
                        {[
                          { name: "Repository Code Quality", wt: "30%", score: 86, color: "from-blue-600 to-cyan-500" },
                          { name: "GitHub Activity Footprint", wt: "25%", score: 92, color: "from-cyan-500 to-blue-600" },
                          { name: "Skills Balance Matrix", wt: "20%", score: 75, color: "from-indigo-600 to-purple-600" },
                          { name: "ATS Resume Match Rate", wt: "15%", score: 80, color: "from-emerald-500 to-teal-500" },
                        ].map((m) => (
                          <div key={m.name} className="text-xs">
                            <div className="flex justify-between text-[11px] mb-1.5 font-semibold">
                              <span className="text-[var(--foreground-secondary)]">{m.name} ({m.wt})</span>
                              <span className="text-[var(--foreground)] font-extrabold">{m.score}/100</span>
                            </div>
                            <div className="h-1.5 w-full bg-[var(--surface-container-highest)] rounded-full overflow-hidden">
                              <div className={`h-full bg-gradient-to-r ${m.color} rounded-full`} style={{ width: `${m.score}%` }} />
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 2. GitHub Analysis */}
                {activeTab === "github" && (
                  <motion.div
                    key="github"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-6"
                  >
                    <div className="grid gap-4 sm:grid-cols-3">
                      {[
                        { label: "Active Repositories", val: "48", desc: "Production Synced" },
                        { label: "Community Stars", val: "1.2K", desc: "Total Stars Earned" },
                        { label: "Recent Commits", val: "342", desc: "Past 90 Days" },
                      ].map((item) => (
                        <div key={item.label} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-4.5 text-center hover:border-[var(--primary)]/30 transition-colors">
                          <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-wider">{item.label}</span>
                          <span className="text-2.5xl font-black text-[var(--foreground)] block mt-1.5 tracking-tight">{item.val}</span>
                          <span className="text-[10px] text-[var(--foreground-secondary)] block mt-1 font-medium">{item.desc}</span>
                        </div>
                      ))}
                    </div>

                    {/* Language charts mock */}
                    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-5 flex items-center justify-between">
                      <div className="space-y-3.5 w-1/2">
                        <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest block">Language Balance</span>
                        <div className="space-y-2">
                          {[
                            { name: "TypeScript", pct: "64%", color: "bg-blue-600" },
                            { name: "Python", pct: "22%", color: "bg-amber-500" },
                            { name: "Rust", pct: "14%", color: "bg-orange-500" },
                          ].map((l) => (
                            <div key={l.name} className="flex items-center gap-2 text-xs">
                              <span className={`h-2.5 w-2.5 rounded-full ${l.color}`} />
                              <span className="text-[var(--foreground-secondary)] font-semibold">{l.name}</span>
                              <span className="text-[var(--foreground)] font-extrabold ml-auto">{l.pct}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                      <div className="flex flex-col items-end gap-2.5 w-1/2">
                        <span className="text-[9px] font-mono text-[var(--foreground-muted)] uppercase font-extrabold">Commit Velocity Map</span>
                        <svg viewBox="0 0 100 30" className="w-full max-w-[160px] h-12 stroke-blue-600 fill-none">
                          <path d="M0,25 Q15,10 30,20 T60,5 T90,15 L100,5" strokeWidth="2.5" strokeLinecap="round" />
                        </svg>
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 3. Resume Analysis */}
                {activeTab === "resume" && (
                  <motion.div
                    key="resume"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-6 md:grid-cols-2"
                  >
                    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-5 flex flex-col justify-between">
                      <div>
                        <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest">ATS Audit Rating</span>
                        <div className="flex items-baseline gap-1.5 mt-3">
                          <span className="text-4xl font-black text-emerald-600">89</span>
                          <span className="text-xs text-[var(--foreground-muted)] font-bold">/100</span>
                        </div>
                        <p className="text-xs text-[var(--foreground-secondary)] leading-relaxed mt-4 font-medium">
                          Your resume structure, header format, and bullet achievements are highly optimized for technical scanners.
                        </p>
                      </div>
                      <div className="mt-4 pt-3.5 border-t border-[var(--border)] text-[10px] text-emerald-600 font-bold flex items-center gap-2">
                        <CheckCircle className="h-4 w-4" />
                        Zero layout errors detected
                      </div>
                    </div>

                    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-5 space-y-4">
                      <div>
                        <span className="text-[9px] font-extrabold text-amber-600 uppercase tracking-widest block mb-2">High Impact Keyword Gaps</span>
                        <p className="text-xs text-[var(--foreground-secondary)] font-medium">
                          Adding these keywords to your project descriptions can improve search relevance:
                        </p>
                      </div>
                      <div className="space-y-2">
                        {[
                          { word: "Kubernetes Orchestration", impact: "High Impact" },
                          { word: "GraphQL Resolvers", impact: "Medium Impact" },
                          { word: "CI/CD Pipeline Build", impact: "High Impact" },
                        ].map((w) => (
                          <div key={w.word} className="flex justify-between items-center text-xs p-2 bg-[var(--surface)] rounded-xl border border-[var(--border)] shadow-xs">
                            <span className="font-mono text-[var(--foreground)] font-bold">{w.word}</span>
                            <span className="text-[8px] uppercase font-extrabold text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full border border-amber-200">{w.impact}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 4. Skill Gaps */}
                {activeTab === "skills" && (
                  <motion.div
                    key="skills"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                  >
                    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-4.5 flex items-center justify-between text-xs">
                      <div>
                        <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] tracking-widest uppercase block">Market Balance Matrix</span>
                        <span className="text-sm font-bold text-[var(--foreground)] mt-1 block">Full-stack Balance: 74%</span>
                      </div>
                      <span className="text-[10px] font-bold text-pink-600 bg-pink-50 border border-pink-200 px-2.5 py-1 rounded-full">Target: Fullstack</span>
                    </div>

                    <div className="space-y-2.5">
                      {[
                        { skill: "Docker & Containerization", priority: "critical", action: "Dockerize local app, write compose scripts" },
                        { skill: "Redis Caching Layer", priority: "important", action: "Integrate Redis caching to backend user profile APIs" },
                        { skill: "AWS S3 / Cloud Bucket Deploy", priority: "optional", action: "Deploy asset pipeline to cloud bucket storage" },
                      ].map((item) => (
                        <div key={item.skill} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-3.5 flex items-center justify-between gap-4 text-xs">
                          <div>
                            <span className="font-bold text-[var(--foreground)] block">{item.skill}</span>
                            <span className="text-[10px] text-[var(--foreground-muted)] mt-1 block">{item.action}</span>
                          </div>
                          <span className={`text-[8px] font-extrabold uppercase tracking-widest px-2.5 py-1 rounded-full border ${
                            item.priority === "critical" ? "bg-red-50 text-red-600 border-red-200" :
                            item.priority === "important" ? "bg-amber-50 text-amber-600 border-amber-200" :
                            "bg-[var(--surface)] text-[var(--foreground-muted)] border-[var(--border)]"
                          }`}>
                            {item.priority}
                          </span>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* 5. Portfolio Score */}
                {activeTab === "portfolio" && (
                  <motion.div
                    key="portfolio"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-4 md:grid-cols-3"
                  >
                    {[
                      { title: "Lighthouse Performance", grade: "96%", desc: "PageSpeed & Asset load speeds", color: "text-emerald-600" },
                      { title: "Design & UX Consistency", grade: "82%", desc: "Responsive layout structure", color: "text-blue-600" },
                      { title: "Semantic Code Audit", grade: "90%", desc: "HTML5 tags & clean DOM size", color: "text-cyan-600" },
                    ].map((card) => (
                      <div key={card.title} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-5 text-center flex flex-col justify-between min-h-[150px] hover:border-emerald-500/30 transition-all duration-300">
                        <div>
                          <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest block">{card.title}</span>
                          <span className={`text-3xl font-black ${card.color} block mt-3.5 tracking-tight`}>{card.grade}</span>
                        </div>
                        <span className="text-[10px] text-[var(--foreground-secondary)] leading-relaxed mt-3.5 block font-medium">{card.desc}</span>
                      </div>
                    ))}
                  </motion.div>
                )}

                {/* 6. Career Readiness */}
                {activeTab === "readiness" && (
                  <motion.div
                    key="readiness"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                  >
                    <div className="grid gap-4 sm:grid-cols-2">
                      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-4.5">
                        <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest block mb-2">Startup Fit</span>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-3xl font-black text-blue-600">92%</span>
                          <span className="text-[9px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full">Highly Ready</span>
                        </div>
                        <p className="text-[10px] text-[var(--foreground-secondary)] leading-relaxed mt-2.5 font-medium">
                          Excellent ship velocity, diverse stack, and high repository creation frequencies align with startup environments.
                        </p>
                      </div>

                      <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-4.5">
                        <span className="text-[9px] font-extrabold text-[var(--foreground-muted)] uppercase tracking-widest block mb-2">Enterprise Fit</span>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-3xl font-black text-purple-600">76%</span>
                          <span className="text-[9px] font-bold text-[var(--foreground-muted)] bg-[var(--surface)] border border-[var(--border)] px-2 py-0.5 rounded-full">Moderately Ready</span>
                        </div>
                        <p className="text-[10px] text-[var(--foreground-secondary)] leading-relaxed mt-2.5 font-medium">
                          Requires adding systematic unit/integration testing portfolios and architecture documentation trees.
                        </p>
                      </div>
                    </div>

                    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface-container-low)] p-4.5 flex items-center justify-between text-xs">
                      <div className="flex items-center gap-2.5">
                        <Compass className="h-4.5 w-4.5 text-purple-600" />
                        <span className="text-[var(--foreground-secondary)] font-semibold">Career Track Focus:</span>
                        <span className="font-bold text-[var(--foreground)]">Fullstack (Web)</span>
                      </div>
                      <span className="text-[10px] font-bold text-emerald-600">Rank: Explorer II</span>
                    </div>
                  </motion.div>
                )}

              </AnimatePresence>
            </div>

            {/* Bottom CTA bar */}
            <div className="mt-6 pt-4 border-t border-[var(--border)] flex items-center justify-between text-xs text-[var(--foreground-secondary)] font-medium">
              <span>Ready to check your actual scores?</span>
              <Link 
                href="/login"
                className="inline-flex items-center gap-1.5 font-bold text-[var(--primary)] hover:underline"
              >
                Scan Profile Now
                <ArrowUpRight className="h-4 w-4" />
              </Link>
            </div>

          </div>

        </div>
      </div>
    </section>
  );
}
